#!/usr/bin/python

import sys

from twisted.python import log

import commit_bot

if __name__ == '__main__':
    if len(sys.argv) != 1:
        raise SystemExit("Usage: %s" % (sys.argv[0],))
    log.startLogging(sys.stdout)
    commit_bot.main()

