#!/usr/bin/python

from twisted.python import usage
from twisted.python.filepath import FilePath
from subprocess import check_call

class Options(usage.Options):
    def parseArgs(self, revno = '37400'):
        self.revno = revno

def main(config):
    dir = FilePath('.')
    if not dir.child('objects').isdir():
        dir.child('objects').createDirectory()
    if not dir.child('refs').isdir():
        dir.child('refs').createDirectory()
    if not dir.child('svn').isdir():
        dir.child('svn').createDirectory()
    dir.child('HEAD').setContent('ref: refs/heads/trunk')
    for key in ['svn-remote.svn.branches-maxRev',
                'svn-remote.svn.tags-maxRev',
                'svn-remote.svn-releases.branches-maxRev']:
        check_call(['git', 'config', '-f', 'svn/.metadata', key, config.revno])

    # Remove this before, in case we've been run before.
    dir.child('refs').child('svn').child('releases').remove()

    check_call(['git', 'fetch', 'fetch'])
    check_call(['git', 'update-ref', '-d', 'refs/svn/trunk'])

    # Remove this after, so that 'git svn fetch svn' can create
    # its stupid 'releases' branch.
    dir.child('refs').child('svn').child('releases').remove()

if __name__ == '__main__':
    config = Options()
    config.parseOptions()
    main(config)
